#!/usr/bin/env bash

[ command -v sudo >/dev/null 2>&1 ] && SUDO=sudo || SUDO=doas
case $BUTTON in
	1) st -e btop & ;;
	6) st -e $SUDO $EDITOR $0 ;;
esac

icon=""
iconcol="#65b1cd"
memory=$(free -h | awk '/Mem/ {print $3}')

printf "%s %s\n" "^c$iconcol^$icon^d^" $memory
