#!/usr/bin/env bash

case $BUTTON in
	1) st -e btop & ;;
esac

icon="🌡"
cpu=$(sensors | awk '/Tctl/ { print $2 }' | sed 's/+//;s/\..*//')

if ! command -v nvidia-smi &> /dev/null; then
	gpu=$(sensors | awk '/junction/ {print $2}' | sed 's/\..*//g;s/+//g')
else
	gpu=$(nvidia-smi | grep -o '[0-9][0-9]C' | sed 's/C//g')
fi

printf "%s %s / %s°C\n" $icon $cpu $gpu
