#!/usr/bin/env bash

[ command -v sudo >/dev/null 2>&1 ] && SUDO=sudo || SUDO=doas
case $BUTTON in
	6) st -e $SUDO $EDITOR $0 ;;
esac

icon=" 🐧"
kernel=$(uname -r | sed 's/-.*//')

printf "%s %s\n" $icon $kernel
