#!/usr/bin/env bash

case $BUTTON in
	1) st -e btop ;;
esac

icon="🌡"
cpu=$(sensors | awk '/Tctl/ { print $2 }' | sed 's/+//;s/\..*//')
gpu=$(sensors | awk '/junction/ {print $2}' | sed 's/\..*//g;s/+//g')

printf "%s %s / %s°C\n" $icon $cpu $gpu
